#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Seems Reasonable!

# Short bio or description (displayed in the header)
description: Trying to understand how computers should act on real world observations. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
future: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     100
sass:
  compressed: true
# Plugins
gems:         ['jekyll-paginate']
